export const modules = [
  {
    key: 'identity-access',
    tag: 'IdentityAccess',
    story: 'R1-02',
    typed: true,
    scenarios: ['SC-R1-AUTH-01', 'SC-R1-AUTH-02', 'SC-R1-AUTH-03', 'SC-R1-SEC-01', 'SC-R1-REL-01'],
    operations: [
      op('post', '/auth/registrations', 'registerAccount', { public: true, idempotent: true, body: 'AuthRegistrationRequest', response: 'CommandAccepted', success: 202, permission: 'account.register' }),
      op('post', '/auth/email-verification-challenges', 'requestEmailVerification', { public: true, optionalSession: true, body: 'OtpChallengeRequest', response: 'CommandAccepted', success: 202, permission: 'account.register' }),
      op('post', '/auth/email-verifications', 'verifyEmail', { public: true, idempotent: true, body: 'EmailVerificationRequest', response: 'Account', permission: 'account.register' }),
      op('post', '/auth/password-sessions', 'loginWithPassword', { public: true, body: 'PasswordSessionRequest', response: 'Session', sessionResponse: true, permission: 'account.authenticate' }),
      op('post', '/auth/otp-challenges', 'requestLoginOtp', { public: true, body: 'OtpChallengeRequest', response: 'CommandAccepted', success: 202, permission: 'account.authenticate' }),
      op('post', '/auth/otp-sessions', 'loginWithOtp', { public: true, body: 'OtpSessionRequest', response: 'Session', sessionResponse: true, permission: 'account.authenticate' }),
      op('get', '/auth/session', 'getCurrentSession', { response: 'Session', permission: 'account.authenticate' }),
      op('delete', '/auth/session', 'logoutCurrentSession', { csrf: true, success: 204, permission: 'account.authenticate' }),
      op('delete', '/auth/sessions', 'logoutAllSessions', { csrf: true, idempotent: true, success: 204, permission: 'account.authenticate' }),
      op('post', '/auth/password-recovery-challenges', 'requestPasswordRecovery', { public: true, body: 'OtpChallengeRequest', response: 'CommandAccepted', success: 202, permission: 'account.recover' }),
      op('post', '/auth/password-resets', 'resetPassword', { public: true, idempotent: true, body: 'PasswordResetRequest', response: 'Account', permission: 'account.recover' }),
      op('put', '/auth/password', 'changePassword', { csrf: true, ifMatch: true, body: 'ChangePasswordRequest', response: 'Account', permission: 'account.recover' }),
      list('/admin/accounts', 'listAccounts', 'account.read', { response: 'AccountPage', queryParameters: [{ name: 'status', schema: ref('AccountStatus') }] }),
      get('/admin/accounts/{accountId}', 'getAccount', 'account.read', { response: 'Account' }),
      action('/admin/accounts/{accountId}/actions/change-status', 'changeAccountStatus', 'account.status.change', { idempotent: true, body: 'ChangeAccountStatusRequest', response: 'Account' }),
      list('/admin/roles', 'listRoles', 'role.read', { response: 'RolePage', queryParameters: [{ name: 'active', schema: { type: 'boolean' } }] }),
      create('/admin/roles', 'createRole', 'role.create', { body: 'CreateRoleRequest', response: 'Role' }),
      list('/admin/permissions', 'listPermissions', 'permission.read', { response: 'PermissionPage', queryParameters: [{ name: 'active', schema: { type: 'boolean' } }] }),
      op('put', '/admin/roles/{roleId}/permissions', 'replaceRolePermissions', { csrf: true, ifMatch: true, body: 'ReplaceRolePermissionsRequest', response: 'Role', permission: 'role.permission.manage' }),
      list('/admin/accounts/{accountId}/role-assignments', 'listAccountRoleAssignments', 'account.role.read', { response: 'AccountRoleAssignmentPage', queryParameters: [{ name: 'status', schema: ref('AccountRoleAssignmentStatus') }, { name: 'effectiveAt', schema: { type: 'string', format: 'date-time' } }] }),
      create('/admin/accounts/{accountId}/role-assignments', 'assignAccountRole', 'account.manage_role', { body: 'AssignAccountRoleRequest', response: 'AccountRoleAssignment' }),
      action('/admin/role-assignments/{assignmentId}/actions/revoke', 'revokeAccountRoleAssignment', 'account.manage_role', { body: 'ReasonCommand', response: 'AccountRoleAssignment' }),
    ],
  },
  {
    key: 'platform-audit', tag: 'PlatformAudit', story: 'R1-02', typed: true, scenarios: ['SC-R1-SEC-01', 'SC-R1-REL-01'], operations: [
      create('/patients/{patientId}/break-glass-grants', 'requestBreakGlassGrant', 'clinical.break_glass', { body: 'BreakGlassGrantRequest', response: 'BreakGlassGrant' }),
      list('/break-glass-grants', 'listBreakGlassGrants', 'audit.read', { response: 'BreakGlassGrantPage', queryParameters: [{ name: 'status', schema: ref('BreakGlassGrantStatus') }, { name: 'patientId', schema: { type: 'string', format: 'uuid' } }, { name: 'requesterAccountId', schema: { type: 'string', format: 'uuid' } }] }),
      action('/break-glass-grants/{grantId}/actions/revoke', 'revokeBreakGlassGrant', 'clinical.break_glass', { body: 'ReasonCommand', response: 'BreakGlassGrant' }),
      action('/break-glass-grants/{grantId}/actions/review', 'reviewBreakGlassGrant', 'audit.break_glass.review', { body: 'ReviewBreakGlassGrantRequest', response: 'BreakGlassGrant' }),
      list('/audit-events', 'listAuditEvents', 'audit.read', { response: 'AuditEventPage', queryParameters: [{ name: 'occurredFrom', schema: { type: 'string', format: 'date-time' } }, { name: 'occurredTo', schema: { type: 'string', format: 'date-time' } }, { name: 'patientId', schema: { type: 'string', format: 'uuid' } }, { name: 'actorAccountId', schema: { type: 'string', format: 'uuid' } }, { name: 'action', schema: { type: 'string', maxLength: 128 } }, { name: 'outcome', schema: ref('AuditOutcome') }, { name: 'correlationId', schema: { type: 'string', maxLength: 128 } }] }),
      get('/audit-events/{auditEventId}', 'getAuditEvent', 'audit.read', { response: 'AuditEvent' }),
    ],
  },
  {
    key: 'catalog', tag: 'Catalog', story: 'R1-03', typed: true, scenarios: ['R1-03-CATALOG-CONSTRAINTS'], operations: [
      ...catalog('departments', 'Department', 'department'),
      ...catalog('rooms', 'Room', 'room'),
      ...catalog('services', 'Service', 'service'),
      list('/services/{serviceId}/prices', 'listServicePrices', 'service_price.read', { response: 'ServicePricePage' }),
      create('/services/{serviceId}/prices', 'createServicePrice', 'service_price.create', { body: 'CreateServicePriceRequest', response: 'ServicePrice' }),
      get('/service-prices/{priceId}', 'getServicePrice', 'service_price.read', { response: 'ServicePrice' }),
      action('/service-prices/{priceId}/actions/end', 'endServicePrice', 'service_price.update', { body: 'EndServicePriceRequest', response: 'ServicePrice' }),
      ...catalog('practitioners', 'Practitioner', 'practitioner'),
      list('/practitioners/{practitionerId}/roles', 'listPractitionerRoles', 'practitioner_role.read', { response: 'PractitionerRolePage' }),
      create('/practitioners/{practitionerId}/roles', 'assignPractitionerRole', 'practitioner_role.create', { body: 'AssignPractitionerRoleRequest', response: 'PractitionerRole' }),
      get('/practitioner-roles/{roleId}', 'getPractitionerRole', 'practitioner_role.read', { response: 'PractitionerRole' }),
      action('/practitioner-roles/{roleId}/actions/revoke', 'revokePractitionerRole', 'practitioner_role.update', { body: 'RevokePractitionerRoleRequest', response: 'PractitionerRole' }),
    ],
  },
  {
    key: 'patient', tag: 'Patient', story: 'R1-04', typed: true, scenarios: ['SC-R1-PAT-01'], operations: [
      create('/patients', 'createPatient', 'patient.create', { body: 'CreatePatientRequest', response: 'Patient' }),
      create('/patients/self', 'createOwnPatient', 'account.authenticate', { body: 'CreatePatientRequest', response: 'Patient' }),
      list('/patients', 'searchPatients', 'patient.search', { response: 'PatientPage', queryParameters: [{ name: 'query', schema: { type: 'string', maxLength: 320 } }] }),
      get('/patients/{patientId}', 'getPatient', 'patient.read', { response: 'Patient' }),
      patch('/patients/{patientId}', 'updatePatient', 'patient.update', { body: 'UpdatePatientRequest', response: 'Patient' }),
      list('/patients/{patientId}/identifiers', 'listPatientIdentifiers', 'patient_identifier.read', { response: 'PatientIdentifierPage' }),
      create('/patients/{patientId}/identifiers', 'addPatientIdentifier', 'patient_identifier.create', { body: 'AddPatientIdentifierRequest', response: 'PatientIdentifier' }),
      action('/patient-identifiers/{identifierId}/actions/verify-manually', 'verifyPatientIdentifierManually', 'identity.link.verify', { body: 'VerifyPatientIdentifierRequest', response: 'PatientIdentifier' }),
      action('/patient-identifiers/{identifierId}/actions/revoke', 'revokePatientIdentifier', 'identity.link.verify', { body: 'RevokePatientIdentifierRequest', response: 'PatientIdentifier' }),
      action('/patient-identifiers/{identifierId}/actions/enter-in-error', 'enterPatientIdentifierInError', 'identity.link.verify', { body: 'PatientIdentifierErrorRequest', response: 'PatientIdentifier' }),
      get('/patients/account-links', 'listMyPatientAccountLinks', 'account.authenticate', { response: 'PatientAccountLinkList' }),
      list('/patients/{patientId}/account-links', 'listPatientAccountLinks', 'patient_account_link.read', { response: 'PatientAccountLinkPage' }),
      create('/patients/{patientId}/account-links', 'linkPatientAccount', 'patient_account_link.create', { body: 'CreatePatientAccountLinkRequest', response: 'PatientAccountLink' }),
      list('/patient-duplicate-candidates', 'listPatientDuplicateCandidates', 'patient_duplicate.review', { response: 'PatientDuplicateCandidatePage', queryParameters: [{ name: 'status', schema: ref('PatientDuplicateCandidateStatus') }] }),
      get('/patient-duplicate-candidates/{candidateId}', 'getPatientDuplicateCandidate', 'patient_duplicate.review', { response: 'PatientDuplicateCandidate' }),
      action('/patient-duplicate-candidates/{candidateId}/actions/review', 'reviewPatientDuplicateCandidate', 'patient_duplicate.review', { body: 'ReviewPatientDuplicateCandidateRequest', response: 'PatientDuplicateCandidate' }),
      action('/patient-duplicate-candidates/{candidateId}/actions/enter-in-error', 'enterPatientDuplicateCandidateInError', 'patient_duplicate.review', { body: 'PatientDuplicateCandidateErrorRequest', response: 'PatientDuplicateCandidate' }),
    ],
  },
  {
    key: 'scheduling-payment', tag: 'SchedulingPayment', story: 'R1-05,R1-06,R1-07', typed: true,
    scenarios: ['SC-R1-BOOK-01', 'SC-R1-BOOK-02', 'SC-R1-BOOK-03', 'SC-R1-BOOK-04', 'SC-R1-PAY-01', 'SC-R1-PAY-02', 'SC-R1-RESCHEDULE-01', 'SC-R1-RESCHEDULE-02'], operations: [
      list('/appointment-slots', 'searchAppointmentSlots', 'appointment_slot.read', { public: true, response: 'AppointmentSlotPage' }),
      get('/appointment-slots/{slotId}', 'getAppointmentSlot', 'appointment_slot.read', { public: true, response: 'AppointmentSlot' }),
      create('/appointment-slots', 'createAppointmentSlot', 'appointment_slot.create', { body: 'CreateAppointmentSlotRequest', response: 'AppointmentSlot' }),
      patch('/appointment-slots/{slotId}', 'updateAppointmentSlot', 'appointment_slot.update', { body: 'UpdateAppointmentSlotRequest', response: 'AppointmentSlot' }),
      action('/appointment-slots/{slotId}/actions/cancel', 'cancelAppointmentSlot', 'appointment_slot.cancel', { idempotent: true, response: 'AppointmentSlot' }),
      create('/slot-holds', 'createSlotHold', 'slot_hold.create', { body: 'SlotHoldRequest', response: 'SlotHold' }),
      get('/slot-holds/{holdId}', 'getSlotHold', 'slot_hold.read', { response: 'SlotHold' }),
      op('delete', '/slot-holds/{holdId}', 'cancelSlotHold', { csrf: true, ifMatch: true, idempotent: true, permission: 'slot_hold.cancel', response: 'SlotHold', success: 200 }),
      create('/slot-holds/{holdId}/payment-intents', 'createPaymentIntent', 'payment_intent.create', { body: 'CreatePaymentIntentRequest', response: 'PaymentIntent' }),
      get('/payment-intents/{paymentIntentId}', 'getPaymentIntent', 'payment_intent.read', { response: 'PaymentIntent' }),
      op('post', '/webhooks/payments/{provider}', 'receivePaymentWebhook', { webhook: true, body: 'PaymentWebhookEvent', response: 'CommandAccepted', success: 202, permission: 'payment.webhook.receive' }),
      op('post', '/mock-payment-intents/{paymentIntentId}/actions/simulate', 'simulateMockPaymentOutcome', { body: 'SimulatePaymentOutcomeRequest', response: 'CommandAccepted', success: 202, permission: 'payment.mock.simulate', idempotent: true, environments: ['local', 'test'] }),
      list('/appointments', 'listAppointments', 'appointment.read'), get('/appointments/{appointmentId}', 'getAppointment', 'appointment.read'),
      action('/appointments/{appointmentId}/actions/reschedule', 'rescheduleAppointment', 'appointment.reschedule', { idempotent: true, body: 'RescheduleAppointmentRequest', response: 'RescheduleAppointmentResponse' }),
      action('/appointments/{appointmentId}/actions/cancel', 'cancelAppointment', 'appointment.cancel', { idempotent: true }),
      action('/appointments/{appointmentId}/actions/mark-no-show', 'markAppointmentNoShow', 'appointment.no_show'),
    ],
  },
  {
    key: 'reception-queue', tag: 'ReceptionQueue', story: 'R1-08,R1-09,R1-13', scenarios: ['SC-R1-CHECKIN-01', 'SC-R1-CHECKIN-02', 'SC-R1-QUEUE-01'], operations: [
      create('/appointments/{appointmentId}/check-ins', 'checkInAppointment', 'checkin.execute'), get('/check-ins/{checkInId}', 'getCheckIn', 'checkin.read'),
      list('/visits', 'listVisits', 'visit.read'), get('/visits/{visitId}', 'getVisit', 'visit.read'),
      action('/visits/{visitId}/actions/complete', 'completeVisit', 'visit.complete', { idempotent: true }),
      action('/visits/{visitId}/actions/cancel', 'cancelVisit', 'visit.cancel'), action('/visits/{visitId}/actions/enter-in-error', 'enterVisitInError', 'visit.enter_in_error'),
      list('/visits/{visitId}/encounters', 'listVisitEncounters', 'encounter.read'), get('/encounters/{encounterId}', 'getEncounter', 'encounter.read'),
      ...['start', 'complete', 'cancel', 'enter-in-error'].map(v => action(`/encounters/{encounterId}/actions/${v}`, `${camel(v)}Encounter`, `encounter.${v.replaceAll('-', '_')}`)),
      list('/queue-entries', 'listQueueEntries', 'queue.read'), get('/queue-entries/{queueEntryId}', 'getQueueEntry', 'queue.read'),
      ...[['call','callQueueEntry'],['start-service','startQueueService'],['defer','deferQueueEntry'],['return-to-waiting','returnQueueEntryToWaiting'],['complete','completeQueueEntry'],['cancel','cancelQueueEntry'],['enter-in-error','enterQueueEntryInError']].map(([v,id]) => action(`/queue-entries/{queueEntryId}/actions/${v}`, id, `queue.${v.replaceAll('-', '_')}`)),
      create('/queue-entries/{queueEntryId}/adjustments', 'adjustQueueEntry', 'queue.adjust', { ifMatch: true }),
      get('/departments/{departmentId}/queue-policy', 'getQueuePolicy', 'queue_policy.read'),
      op('put', '/departments/{departmentId}/queue-policy', 'putQueuePolicy', { csrf: true, idempotent: true, permission: 'queue_policy.manage' }),
      list('/queue-screen', 'getQueueScreen', 'queue_screen.read'),
    ],
  },
  {
    key: 'clinical-care', tag: 'ClinicalCare', story: 'R1-10,R1-11', scenarios: ['SC-R1-CLIN-01', 'SC-R1-CLIN-02', 'SC-R1-BILL-01'], operations: [
      list('/encounters/{encounterId}/clinical-notes', 'listEncounterClinicalNotes', 'clinical.note.read'),
      create('/encounters/{encounterId}/clinical-notes', 'createClinicalNote', 'encounter.write', { body: 'ClinicalDraftRequest' }),
      get('/clinical-notes/{noteId}', 'getClinicalNote', 'clinical.note.read'), list('/clinical-notes/{noteId}/versions', 'listClinicalNoteVersions', 'clinical.note.read'),
      get('/clinical-note-versions/{versionId}', 'getClinicalNoteVersion', 'clinical.note.read'), patch('/clinical-note-versions/{versionId}', 'updateClinicalNoteDraft', 'encounter.write', { body: 'ClinicalDraftRequest' }),
      action('/clinical-note-versions/{versionId}/actions/finalize', 'finalizeClinicalNoteVersion', 'clinical.note.finalize', { idempotent: true }),
      action('/clinical-note-versions/{versionId}/actions/amend', 'amendClinicalNoteVersion', 'clinical.version.amend', { idempotent: true }),
      action('/clinical-note-versions/{versionId}/actions/enter-in-error', 'enterClinicalNoteVersionInError', 'clinical.version.enter_in_error'),
      list('/encounters/{encounterId}/diagnoses', 'listEncounterDiagnoses', 'diagnosis.read'),
      create('/encounters/{encounterId}/diagnoses', 'createDiagnosis', 'encounter.write', { body: 'DiagnosisDraftRequest' }),
      get('/diagnoses/{diagnosisId}', 'getDiagnosis', 'diagnosis.read'), list('/diagnoses/{diagnosisId}/versions', 'listDiagnosisVersions', 'diagnosis.read'),
      get('/diagnosis-versions/{versionId}', 'getDiagnosisVersion', 'diagnosis.read'), patch('/diagnosis-versions/{versionId}', 'updateDiagnosisDraft', 'encounter.write', { body: 'DiagnosisDraftRequest' }),
      action('/diagnosis-versions/{versionId}/actions/finalize', 'finalizeDiagnosisVersion', 'diagnosis.finalize', { idempotent: true }),
      action('/diagnosis-versions/{versionId}/actions/amend', 'amendDiagnosisVersion', 'clinical.version.amend', { idempotent: true }),
      action('/diagnosis-versions/{versionId}/actions/enter-in-error', 'enterDiagnosisVersionInError', 'clinical.version.enter_in_error'),
      list('/encounters/{encounterId}/service-deliveries', 'listEncounterServiceDeliveries', 'service_delivery.read'),
      create('/encounters/{encounterId}/service-deliveries', 'createServiceDelivery', 'service_delivery.create'),
      get('/service-deliveries/{deliveryId}', 'getServiceDelivery', 'service_delivery.read'),
      action('/service-deliveries/{deliveryId}/actions/perform', 'performServiceDelivery', 'service_delivery.perform', { idempotent: true }),
      action('/service-deliveries/{deliveryId}/actions/cancel', 'cancelServiceDelivery', 'service_delivery.cancel'),
      action('/service-deliveries/{deliveryId}/actions/enter-in-error', 'enterServiceDeliveryInError', 'service_delivery.enter_in_error'),
    ],
  },
  {
    key: 'billing-payment', tag: 'BillingPayment', story: 'R1-11,R1-12,R1-13', scenarios: ['SC-R1-BILL-01', 'SC-R1-BILL-02'], operations: [
      get('/visits/{visitId}/billing-account', 'getVisitBillingAccount', 'billing.read'), get('/billing-accounts/{accountId}', 'getBillingAccount', 'billing.read'),
      list('/billing-accounts/{accountId}/ledger', 'listBillingLedgerEntries', 'billing.read'), list('/billing-accounts/{accountId}/charges', 'listBillingAccountCharges', 'billing.read'),
      get('/charge-items/{chargeItemId}', 'getChargeItem', 'billing.read'),
      create('/payments', 'recordCounterPayment', 'payment.capture', { body: 'PaymentRequest' }), list('/payments', 'listPayments', 'payment.read'), get('/payments/{paymentId}', 'getPayment', 'payment.read'),
      create('/billing-accounts/{accountId}/payment-allocations', 'allocatePayment', 'payment.allocate', { ifMatch: true }),
      list('/billing-accounts/{accountId}/payment-allocations', 'listPaymentAllocations', 'billing.read'),
      action('/billing-accounts/{accountId}/actions/close', 'closeBillingAccount', 'billing.close', { idempotent: true }),
      action('/billing-accounts/{accountId}/actions/reopen', 'reopenBillingAccount', 'billing.reopen'),
    ],
  },
  {
    key: 'notification', tag: 'Notification', story: 'R1-14', scenarios: ['R1-14-NOTIFICATION-RELIABILITY'], operations: [
      list('/notifications', 'listMyNotifications', 'notification.read'), get('/notifications/{notificationId}', 'getMyNotification', 'notification.read'),
      action('/notifications/{notificationId}/actions/cancel', 'cancelNotification', 'notification.cancel'),
    ],
  },
]

function op(method, path, operationId, options = {}) { return { method, path, operationId, ...options } }
function get(path, id, permission, options = {}) { return op('get', path, id, { permission, ...options }) }
function list(path, id, permission, options = {}) { return op('get', path, id, { permission, list: true, ...options }) }
function create(path, id, permission, options = {}) { return op('post', path, id, { permission, csrf: true, idempotent: true, ...options }) }
function patch(path, id, permission, options = {}) { return op('patch', path, id, { permission, csrf: true, ifMatch: true, ...options }) }
function action(path, id, permission, options = {}) { return op('post', path, id, { permission, csrf: true, ifMatch: true, ...options }) }
function catalog(plural, singular, permission) {
  return [
    list(`/${plural}`, `list${singular}s`, `${permission}.read`, { response: `${singular}Page` }),
    create(`/${plural}`, `create${singular}`, `${permission}.create`, { body: `Create${singular}Request`, response: singular }),
    get(`/${plural}/{${permission}Id}`, `get${singular}`, `${permission}.read`, { response: singular }),
    patch(`/${plural}/{${permission}Id}`, `update${singular}`, `${permission}.update`, { body: `Update${singular}Request`, response: singular }),
    action(`/${plural}/{${permission}Id}/actions/deactivate`, `deactivate${singular}`, `${permission}.update`, { response: singular }),
  ]
}
function camel(value) { return value.split('-').map((x, i) => i ? x[0].toUpperCase() + x.slice(1) : x).join('') }
function ref(schema) { return { $ref: `#/components/schemas/${schema}` } }
